/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pipeline;

import mongodb.BulkWriteInsert;
import mongodb.MongoDBSetup;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        MongoDBSetup setupMongo = new MongoDBSetup();
        BulkWriteInsert.doBulkInsert(setupMongo.getCollection());
    }
}
